name: spa_beauty
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  easy_localization: ^3.0.0
  flutter_launcher_icons: "^0.9.0"
  firebase_core: ^1.14.1
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.2.12
  firebase_auth: ^3.3.14
  firebase_messaging: ^11.2.13
  lottie: ^1.0.1
  overlay_support: ^1.2.1
  toast: ^0.1.5
  http: any
  provider: ^6.0.0
  cached_network_image: ^3.1.0
  date_picker_timeline: ^1.2.3
  flutter_rating_bar: ^4.0.0
  cool_alert: ^1.1.0
  stripe_payment: ^1.1.4
  future_progress_dialog: ^0.2.0
  sn_progress_dialog: ^1.0.1
  awesome_dialog: ^2.1.0
  webview_flutter: ^2.0.12
  google_sign_in: ^5.0.5
  flutter_facebook_auth: ^3.5.0
  flutter_facebook_login: ^3.0.0
  url_launcher:
  maps_launcher: ^2.0.1
  share: ^2.0.4
  smooth_page_indicator: ^0.2.3
  shared_preferences: ^2.0.6
  image_picker: ^0.8.1+3
  flutter_open_whatsapp: ^0.1.2
  network_to_file_image: ^3.0.0
  path_provider: ^2.0.2
  badges: ^2.0.1
  carousel_slider: ^4.0.0
  day_night_switcher: ^0.2.0+1
  multi_masked_formatter: ^0.1.0
  flutter_local_notifications: ^8.2.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  fonts:
    - family: Georgia Italic
      fonts:
        - asset: assets/fonts/Georgia Bold Italic font.ttf

    - family: Georgia Bold
      fonts:
        - asset: assets/fonts/georgia bold.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito.ttf

    - family: Georgia Seriffic
      fonts:
        - asset: assets/fonts/seriffic.ttf

    - family: Georgia Regular
      fonts:
        - asset: assets/fonts/Georgia Regular font.ttf


    #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
